config/routes.rb
Rails.application.routes.draw do
  root to: 'starts#index'
  resources :starts, only: %i[index]
  resources :users
  resources :beats
  resources :scores, only: %i[create destroy]
  resources :mypage, only: %i[index]

  get 'explain', to: 'starts#explain'
  get 'terms', to: 'starts#terms'
  get 'privacy', to: 'starts#privacy'
  get 'contact', to: 'starts#contact'
  get '/sitemap', to: redirect('https://s3-ap-northeast-1.amazonaws.com/muscle-beat/sitemaps/sitemap.xml.gz')

  get 'login', to: 'user_sessions#new', as: :login
  post 'login', to: 'user_sessions#create'
  post 'logout', to: 'user_sessions#destroy', as: :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beat.rb
# == Schema Information
#
# Table name: beats
#
#  id                   :bigint           not null, primary key
#  gif                  :string           not null
#  level                :integer          not null
#  music                :string           not null
#  notes                :string           not null
#  thumbnail            :string           not null
#  title                :string           not null
#  training_description :string           not null
#  training_muscle      :string           not null
#  url                  :string           not null
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  user_id              :bigint           not null
#
# Indexes
#
#  index_beats_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Beat < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :url, presence: true
  validates :training_muscle, presence: true
  validates :level, presence: true
  validates :thumbnail, presence: true
  validates :training_description, presence: true
  validates :gif, presence: true
  validates :music, presence: true
  validates :notes, presence: true

  enum level: { nomal: 0, hard: 1 }

  mount_uploader :thumbnail, ThumbnailUploader
  mount_uploader :gif, GifUploader
  mount_uploader :music, MusicUploader
  mount_uploader :notes, NotesUploader
end

app/models/score.rb
# == Schema Information
#
# Table name: scores
#
#  id         :bigint           not null, primary key
#  score      :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  beat_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_scores_on_beat_id  (beat_id)
#  index_scores_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (beat_id => beats.id)
#  fk_rails_...  (user_id => users.id)
#
class Score < ApplicationRecord
  belongs_to :user
  belongs_to :beat

  validates :score, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :bigint           not null, primary key
#  crypted_password :string
#  role             :integer          default("general"), not null
#  salt             :string
#  user_name        :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_users_on_user_name  (user_name) UNIQUE
#
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :beats, dependent: :destroy
  has_many :scores, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: lambda {
                                                          new_record? || changes[:crypted_password]
                                                        }
  validates :user_name, uniqueness: true, length: { maximum: 4 }, presence: true

  enum role: { general: 0, admin: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def not_authenticated
    redirect_to login_path, notice: 'ログインが必要です！'
  end

  def user_not_authorized
    redirect_to beats_path, notice: '権限がありません'
  end
end

app/controllers/beats_controller.rb
class BeatsController < ApplicationController
  skip_before_action :require_login, only: %i[index show]
  before_action :set_beat, only: %i[show edit update destroy]
  before_action :authorize_beat, only: %i[index new create]

  def index
    @beats_hard = Beat.hard
    @beats_nomal = Beat.nomal
  end

  def show; end

  def new
    @beat = Beat.new
  end

  def edit; end

  def create
    @beat = current_user.beats.build(beat_params)

    if @beat.save
      redirect_to(:beats, success: 'ビートを追加しました！')
    else
      flash.now[:danger] = 'ビートを追加できませんでした…。'
      render 'new'
    end
  end

  def update
    if @beat.update(beat_params)
      redirect_to beats_path, notice: 'ビートを更新しました！'
    else
      render :beats, status: :unprocessable_entity
    end
  end

  def destroy
    @beat.destroy
    redirect_to beats_path, notice: 'ビートを削除しました！'
  end

  private

  def set_beat
    @beat = Beat.find(params[:id])
    authorize @beat
  end

  def authorize_beat
    authorize Beat
  end

  def beat_params
    params.require(:beat).permit(:title, :url, :training_muscle, :level, :user_id, :thumbnail,
                                 :training_description, :gif, :music, :notes)
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def index
    @scores = Score.includes(:beat).where(user_id: current_user.id).order(created_at: "DESC")
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  protect_from_forgery

  def create
    @score = Score.new(score_params)
    @score.save!
  end

  private

  def score_params
    params.permit(:score, :user_id, :beat_id)
  end
end

app/controllers/starts_controller.rb
class StartsController < ApplicationController
  skip_before_action :require_login

  def index; end
  def explain; end
  def terms; end
  def privacy; end
  def contact; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def create
    @user = login(params[:user_name], params[:password])

    if @user
      redirect_to beats_path, notice: 'ログインしました！'
    else
      flash.now[:notice] = 'ログインに失敗しました…。'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to beats_path, notice: 'ログアウトしました！'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :require_login, only: %i[new create]
  before_action :authorize_user, only: %i[index new create]

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      auto_login(@user)
      redirect_to beats_path, notice: 'ユーザーを登録しました！'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_url(@user), notice: 'ユーザーを登録できませんでした…。'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: 'ユーザーを削除しました！'
  end

  private

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  def authorize_user
    authorize User
  end

  def user_params
    params.require(:user).permit(:user_name, :role, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'Muscle Beat',
      title: 'MuscleBeat - 筋トレ×音ゲー×EDMの新感覚トレーニングアプリ',
      reverse: true,
      charset: 'utf-8',
      description: '筋トレ×音ゲー×EDMの新感覚トレーニングアプリMuscle Beat（マッスルビート）| １分間でノリノリシェイプアップ！HIITトレーニングを採用した最新鋭トレーニングを提供します！',
      keywords: '筋トレ,ダイエット,トレーニングアプリ,筋トレアプリ,ダイエットアプリ',
      canonical: request.original_url,
      separator: '|',
      icon: [
        { href: image_url('favicon.ico') },
        { href: image_url('icon.png'), rel: 'apple-touch-icon', sizes: '180x180',
          type: 'image/png' }
      ],
      og: {
        site_name: 'MuscleBeat - 筋トレ×音ゲー×EDMの新感覚トレーニングアプリ',
        title: 'MuscleBeat - 筋トレ×音ゲー×EDMの新感覚トレーニングアプリ',
        description: '１分間でシェイプアップ！ノリノリ筋トレで高得点を目指せ！',
        type: 'website',
        url: request.original_url,
        image: image_url('ogp.png'),
        locale: 'ja_JP'
      },
      twitter: {
        card: 'summary_large_image',
        site: '@ji_bi__'
      }
    }
  end
end

app/views/beats/_form.html.erb
<div class="form_wrapper">
  <%= form_with(model: beat) do |form| %>
    <% if beat.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(beat.errors.count, "error") %> prohibited this beat from being saved:</h2>

        <ul>
          <% beat.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :url %>
      <%= form.text_field :url %>
    </div>

    <div class="field">
      <%= form.label :training_muscle %>
      <%= form.text_field :training_muscle %>
    </div>

    <div class="field">
      <%= form.label :level %>
      <%= form.select :level, [ ["nomal"], ["hard"]] %>
    </div>

    <div class="field">
      <%= form.label :thumbnail %>
      <%= form.file_field :thumbnail %>
    </div>

    <div class="field">
      <%= form.label :training_description %>
      <%= form.text_area :training_description, size: "40x10" %>
    </div>

    <div class="field">
      <%= form.label :gif %>
      <%= form.file_field :gif %>
    </div>

    <div class="field">
      <%= form.label :music %>
      <%= form.file_field :music %>
    </div>

    <div class="field">
      <%= form.label :notes %>
      <%= form.file_field :notes %>
    </div>


    <div class="actions">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/beats/edit.html.erb
<h1>Editing Beat</h1>

<%= render 'form', beat: @beat %>

<%= link_to 'Show', @beat %> |
<%= link_to 'Back', beats_path %>

app/views/beats/index.html.erb
<div class="index-wrapper">
  <div class="flash">
    <div id="notice"><%= flash[:notice] %></div>
  </div>

  <h1 class="ttl beats-ttl">All Beats</h1>

  <%= render 'shared/humberger' %>

  <div class="level-wrapper">
    <p>Now Level</p>
    <input id="levelbutton" class="btn" type="button" value="Hard" onclick="clickBtn1()" />
  </div>


  <div class="beats-wrapper slider" id="hard">
    <% @beats_hard.each do |beat| %>
      <div class="card mb-3" style="max-width: 540px;">
        <%# ↓turbolinkを無効にして画面遷移時にJSを読み込ませる↓ %>
        <%= link_to beat, class: 'beat-link', data: {"turbolinks" => false} do %>
          <div class="row g-0">
            <div class="col-md-4">
              <%= image_tag beat.thumbnail.url, class: 'img-fluid rounded-start' %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"><span class="fz-rem">曲名：</span><span class="beat-ttl"><%= beat.title %></span></h5>
                <p class="card-text">筋トレ部位：<span class="training-muscle fz-rem"><%= beat.training_muscle %></span></p>

                <%# 動的ランキング機能 %>
                <p class="card-text ranking-btn-<%= beat.id %>"><a class="ranking-btn">ランキング</a></p>
                  <ul class="ranking-pop ranking-pop-<%= beat.id %>">
                    <ul class="">
                      <li class="ranking-ttl"><%= beat.title %></li>
                    </ul>
                    <ul>
                      <% Score.includes(:user).where(beat_id: beat.id).limit(5).order(score: :desc).each_with_index do |rank, i| %>
                        <ul class="ranking-contents flex">
                          <li class="ranking-rank"><%= i + 1 %></li>
                          <li><%= rank.score %></li>
                          <li><%= rank.user.user_name %></li>
                        </ul>
                      <% end %>
                      <div class="ranking-btn-<%= beat.id %> ranking-btn">閉じる</div>
                    </ul>
                  </ul>

                  <script>
                    $('.ranking-btn-<%= beat.id %>').click(function() {
                      $(this).toggleClass('active');

                      if ($(this).hasClass('active')) {
                        $('.ranking-pop-<%= beat.id %>').fadeToggle(200);
                      } else {
                        $('.ranking-pop-<%= beat.id %>').fadeToggle(200);
                      }
                    });
                  </script>

                <% if current_user && current_user.admin? %>
                  <%= link_to '編集', edit_beat_path(beat), class: "lime" %>
                  <%= link_to '削除', beat_path(beat), method: :delete, data: {confirm: 'Beatを削除しますか？'}, class: "lime" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="card mb-3" style="max-width: 540px;">
      <div class="row g-0">
        <div class="col-md-4">
          <%= image_tag 'ogp.png', class: 'img-fluid rounded-start' %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><span class="beat-ttl">First→</span></h5>
            <h5 class="card-title"><span class="training-muscle">←Last</span></h5>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="beats-wrapper slider" id="nomal">
    <% @beats_nomal.each do |beat| %>
      <div class="card mb-3" style="max-width: 540px;">
        <%# ↓turbolinkを無効にして画面遷移時にJSを読み込ませる↓ %>
        <%= link_to beat, class: 'beat-link', data: {"turbolinks" => false} do %>
          <div class="row g-0">
            <div class="col-md-4">
              <%= image_tag beat.thumbnail.url, class: 'img-fluid rounded-start' %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"><span class="fz-rem">曲名：</span><span class="beat-ttl"><%= beat.title %></span></h5>
                <p class="card-text">筋トレ部位：<span class="training-muscle fz-rem"><%= beat.training_muscle %></span></p>

                <%# 動的ランキング機能 %>
                <p class="card-text ranking-btn-<%= beat.id %>"><a class="ranking-btn">ランキング</a></p>
                  <ul class="ranking-pop ranking-pop-<%= beat.id %>">
                    <ul class="">
                      <li class="ranking-ttl"><%= beat.title %></li>
                    </ul>
                    <ul>
                      <% Score.includes(:user).where(beat_id: beat.id).limit(5).order(score: :desc).each_with_index do |rank, i| %>
                        <ul class="ranking-contents flex">
                          <li class="ranking-rank"><%= i + 1 %></li>
                          <li><%= rank.score %></li>
                          <li><%= rank.user.user_name %></li>
                        </ul>
                      <% end %>
                      <div class="ranking-btn-<%= beat.id %> ranking-btn">閉じる</div>
                    </ul>
                  </ul>

                  <script>
                    $('.ranking-btn-<%= beat.id %>').click(function() {
                      $(this).toggleClass('active');

                      if ($(this).hasClass('active')) {
                        $('.ranking-pop-<%= beat.id %>').fadeToggle(200);
                      } else {
                        $('.ranking-pop-<%= beat.id %>').fadeToggle(200);
                      }
                    });
                  </script>

                <% if current_user && current_user.admin? %>
                  <%= link_to '編集', edit_beat_path(beat), class: "lime" %>
                  <%= link_to '削除', beat_path(beat), method: :delete, data: {confirm: 'Beatを削除しますか？'}, class: "lime" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="card mb-3" style="max-width: 540px;">
      <div class="row g-0">
        <div class="col-md-4">
          <%= image_tag 'ogp.png', class: 'img-fluid rounded-start' %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><span class="beat-ttl">First→</span></h5>
            <h5 class="card-title"><span class="training-muscle">←Last</span></h5>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% if current_user && current_user.admin? %>
    <%= link_to 'New Beat', new_beat_path, class: "lime" %>
  <% end %>
</div>

<script>
//レベル切り替えボタン（随時styleを読み取るのでwebpackerに入れない）
document.getElementById("hard").style.display ="block";
document.getElementById("nomal").style.display ="none";

function clickBtn1(){
	const hard = document.getElementById("hard");
  const nomal = document.getElementById("nomal");
  const level = document.getElementById("levelbutton");

	if(hard.style.display=="block"){
		// noneで非表示
		hard.style.display ="none";
		nomal.style.display ="block";
    levelbutton.value = "Nomal"
	}else{
		// blockで表示
		hard.style.display ="block";
		nomal.style.display ="none";
    levelbutton.value = "Hard"
	}
}
</script>

app/views/beats/new.html.erb
<h1>New Beat</h1>

<%= render 'form', beat: @beat %>

<%= link_to 'Back', beats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MuscleBeat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# favicon %>
    <%= favicon_link_tag('favicon.ico') %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-173084008-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-173084008-2');
    </script>

    <%# metaタグ %>
    <%= display_meta_tags(default_meta_tags) %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# axiosの導入 %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.27.1/axios.min.js"></script>
    <%# slick導入 %>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css">
    <script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body class="<%= controller.controller_name %>">

    <%= yield %>

  </body>
</html>

app/views/mypage/index.html.erb
<div class="mypage-wrapper">

  <%= render 'shared/humberger' %>

  <h1 class="ttl">MyPage</h1>

  <h3 class="name"><%= current_user.user_name %></h3>

  <table class="mypage-table">
    <thead>
      <tr>
        <th>日時</th>
        <th class="mypage-pink">スコア</th>
        <th>曲名</th>
        <th class="mypage-pink">部位</th>
        <th>レベル</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @scores.each do |score| %>
        <tr>
          <td><%= l score.created_at %></td>
          <td class="mypage-pink"><%= score.score %></td>
          <td><%= score.beat.title %></td>
          <td class="mypage-pink"><%= score.beat.training_muscle %></td>
          <td><%= score.beat.level %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="footer-fixed">
  <%= render 'shared/footer' %>
</div>

app/views/shared/_footer.html.erb
<footer>
  <ul class="flex">
    <li><%= link_to '利用規約', terms_path %></li>
    <li><%= link_to 'プライバシーポリシー', privacy_path %></li>
    <li><%= link_to 'お問合せ', contact_path %></li>
  </ul>
  <small class="copyright">&copy; 2022 Muscle Beat</small>
</footer>

app/views/shared/_humberger.html.erb
<%# ハンバーガーメニュー %>
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>
  <nav class="globalMenuSp">
    <% if current_user && current_user.admin? %>
      <ul>
        <li><%= link_to "Muscle Beat", root_path %></li>
        <li><%= link_to "使い方", explain_path %></li>
        <li><%= link_to "ビート一覧", beats_path %></li>
        <li><%= link_to "マイページ", mypage_index_path %></li>
        <li><%= link_to "ログアウト", :logout, method: :post %></li>
        <li><%= link_to "ユーザー一覧", users_path %></li>
      </ul>
    <% elsif current_user %>
      <ul>
        <li><%= link_to "Muscle Beat", root_path %></li>
        <li><%= link_to "使い方", explain_path %></li>
        <li><%= link_to "ビート一覧", beats_path %></li>
        <li><%= link_to "マイページ", mypage_index_path %></li>
        <li><%= link_to "ログアウト", :logout, method: :post %></li>
      </ul>
    <% else %>
      <ul>
        <li><%= link_to "Muscle Beat", root_path %></li>
        <li><%= link_to "使い方", explain_path %></li>
        <li><%= link_to "ビート一覧", beats_path %></li>
        <li><%= link_to "ログイン", :login %></li>
        <li><%= link_to "新規登録", new_user_path %></li>
      </ul>
    <% end %>
  </nav>

app/views/starts/explain.html.erb
<%= render 'shared/humberger' %>

<h1 class="ttl">Explain</h1>

<div class="card mb-3 explain-wrapper" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title mb-30">使い方</h5>
        <p class="card-text explain-text">1. 音が出ます！<span class="explain-text-pink">マナーモード</span>と<span class="explain-text-pink">画面の自動回転機能</span>を<span class="explain-text-pink">オフ</span>にしてください！</p>
        <p class="card-text explain-text">2. 下ボタンをクリックして<span class="explain-text-pink">「動作と方向へのアクセス」</span>を許可してください！</p>
        <div class="btn btn-index" onClick="deviceMotionRequest()">クリック</div>
        <p class="card-text explain-text mt-45">3. <span class="explain-text-pink">プレイ画面</span>の説明は画像の通りです！</p>
        <div class="col-md-4">
          <%= image_tag 'explain1.png', class: 'img-fluid rounded-start' %>
        </div>
        <p class="card-text explain-text mt-45">4. <span class="explain-text-pink">曲選択画面</span>の説明は画像の通りです！</p>
        <div class="col-md-4">
          <%= image_tag 'explain2.png', class: 'img-fluid rounded-start' %>
        </div>
        <p class="card-text explain-text mt-45">5. 1~4の確認ができたら、下のボタンをクリックして<span class="explain-text-pink fz-rem">GAME START!!!</span></p>

        <%= link_to beat_path(9), data: {"turbolinks" => false} do %>
          <div class="btn btn-index mt-45 fz-rem">GAME START</div><br>
        <% end %>
        <%= link_to beats_path do %>
          <div class="btn btn-index2 fz-rem mt-20">曲を選択する!!</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/starts/index.html.erb
<div class="top-wrapper">
  <h1 class="ttl">Muscle Beat</h1>

  <%= image_tag 'machoman', size: '230x386', class: 'machoman' %>

  <%= link_to explain_path do %>
    <div class="btn start-btn">START</div>
  <% end %>
</div>

app/views/user_sessions/_form.html.erb
<div class="user-form">
  <%= form_with url: login_path, method: :post do |f| %>
    <div class="field">
      <%= f.label :user_name, 'ユーザーネーム' %><br>
      <%= f.text_field :user_name %>
    </div>
    <div class="field">
      <%= f.label :password, 'パスワード' %><br>
      <%= f.password_field :password %>
    </div>
    <div class="actions">
      <%= f.submit "ログイン", class: 'btn btn-index' %>
    </div>
  <% end %>
</div>

app/views/user_sessions/new.html.erb
<div class="user-wrapper">
  <div class="flash">
    <div id="notice"><%= flash[:notice] %></div>
  </div>
  <%= render 'shared/humberger' %>

  <h1 class="ttl">Login</h1>

  <%= render 'form' %>

  <br>
  <%= link_to '新規登録ページへ', new_user_path, class: 'user-link' %>
</div>

<div class="footer-fixed">
  <%= render 'shared/footer' %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_name %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @users %>
<br>

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<p>
  <strong>User name:</strong>
  <%= @user.user_name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>